jQuery( function($) {

	if ( ! localStorage.getItem( 'wpcom-auth-token' ) ) {
		// bail
		return;
	}

	// get current page
	var filename = window.location.pathname.substring( window.location.pathname.lastIndexOf( '/' ) + 1 );

	$( '#navbar ').replaceWith ( $( document.createElement( "nav" ) )
		.attr( "id", "navbar" )
		.addClass( "navbar navbar-default navbar-static-top" )
		.append( $( document.createElement( "div" ) )
			.addClass( "container-fluid" )
			.append( $( document.createElement( "div" ) )
				.addClass( "navbar-header" )
				.append( $( document.createElement( "button" ) )
					.attr( "type", "button" )
					.addClass( "navbar-toggle collapsed" )
					.attr( "data-toggle", "collapse" )
					.attr( "data-target", "#navbar-open" )
					.attr( "aria-expanded", "false" )
					.append( $( document.createElement( "span" ) )
						.addClass( "sr-only" )
						.text( "Toggle navigation" )
					)
					.append( $( document.createElement( "span" ) ).addClass( "icon-bar" ) )
					.append( $( document.createElement( "span" ) ).addClass( "icon-bar" ) )
					.append( $( document.createElement( "span" ) ).addClass( "icon-bar" ) )
				)
				.append( $( document.createElement( "span" ) )
					.addClass( "navbar-brand" )
					.text( "amanuensis" )
				)
			)
			.append( $( document.createElement( "div" ) )
				.attr( "id", "navbar-open" )
				.addClass( "collapse navbar-collapse" )
				.append( $( document.createElement( "ul" ) )
					.addClass( "nav navbar-nav" )
					.append( $( document.createElement( "li" ) )
						.addClass( function() { return filename == '' ? 'active' : ''; } )
						.css( "min-width", "105px" )
						.append( $( document.createElement( "a" ) )
							.attr( "href", "./" )
							.text( "Inbox " )
							.append( $ ( document.createElement( "span" ) )
								.attr( "id", "results-count" )
								.addClass( "badge" )
								.text( localStorage.inboxCount )
							)
						)
					)
					.append( $( document.createElement( "li" ) )
						.addClass( function() { return filename == 'add.html' ? 'active' : ''; } )
						.append( $( document.createElement( "a" ) )
							.attr( "href", "add.html" )
							.text( "Add" )
						)
					)
					.append( $( document.createElement( "li" ) )
						.addClass( function() { return filename == 'import.html' ? 'active' : ''; } )
						.append( $( document.createElement( "a" ) )
							.attr( "href", "import.html" )
							.text( "Import" )
						)
					)
				)
			)
		)
	);

} );